const houses = [
    {
        name: "Lindlinghof",
        location: "Hinterglemm, Salzburg",
        country: "Austria",
        lat: 47.37739, lng: 12.5758,
        rank: 1, score: 38, beds: 36, rooms: 11,
        elevation: "1020m",
        drive: "2h 20min", driveKm: 200, trainTime: "~4h", trainChanges: "1-2",
        trainNotes: "Train to Zell am See, then bus",
        skiArea: "Saalbach Skicircus", pisteKm: 270, lifts: 70, dayPass: "\u20ac65.50",
        skiNotes: "Austria's biggest interconnected area",
        price: "On request", priceModel: "On request",
        sauna: true, saunaDetails: "140m\u00b2 wellness: Finnish, herbal, infrared",
        kitchen: true, ensuite: true, wifi: false, parking: true, gameRoom: true,
        strengths: "140m\u00b2 wellness spa, 270km Saalbach skiing, best NYE atmosphere, all ensuite, towels + bedding included",
        warnings: "Prices on request \u2014 need to contact. Ski pass expensive (\u20ac425/6-day)",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/lindlinghof-stephanie-%26-christoph-hasenauer-hinterglemm-Oesterreich-hs12056.html",
        image: "https://www-lindlinghof-at.b-cdn.net/wp-content/uploads/2020/03/JFK-Lindlinghof-Winter-Aussen-0010-scaled.jpg",
        tier: "top"
    },
    {
        name: "Ferienhaus Maroldenhof",
        location: "Saalbach-Hinterglemm, Salzburg",
        country: "Austria",
        lat: 47.37501, lng: 12.543747,
        rank: 2, score: 37, beds: 24, rooms: 12,
        elevation: "1003m",
        drive: "2h 20min", driveKm: 180, trainTime: "~3h30", trainChanges: "1-2",
        trainNotes: "Train to Zell am See, then bus",
        skiArea: "Saalbach Skicircus", pisteKm: 270, lifts: 70, dayPass: "\u20ac65.50",
        skiNotes: "Same Saalbach area as Lindlinghof",
        price: "\u20ac1,230\u20131,640/night", priceModel: "Flat rate",
        sauna: true, saunaDetails: "Yes + infrared",
        kitchen: true, ensuite: true, wifi: true, parking: true, gameRoom: false,
        strengths: "Two chalets (historic 1707 + modern 2019), 9 ensuite rooms, great NYE scene, Joker Card",
        warnings: "Only 24 beds \u2014 too small for 30. Ski pass \u20ac425/6-day",
        dealbreaker: "Only 24 beds",
        link: "https://www.gruppenhaus.de/ferienhaus-maroldenhof-andrea-und-michael-hasenauer-saalbach-hinterglemm-hs10683.html",
        image: "https://www.gruppenhaus.de/mx_10683_a_5754_Saalbach-Hinterglemm_Ferienhaus+Maroldenhof_Maroldenweg+4.webp?q=00000000000000",
        tier: "top"
    },
    {
        name: "Klammrast",
        location: "Wildsch\u00f6nau-Oberau, Tirol",
        country: "Austria",
        lat: 47.443864, lng: 12.049792,
        rank: 4, score: 35, beds: 44, rooms: 15,
        elevation: "936m",
        drive: "1h 20min", driveKm: 120, trainTime: "~3h", trainChanges: "1-2",
        trainNotes: "Train to W\u00f6rgl, then bus 4064",
        skiArea: "Ski Juwel Alpbachtal Wildsch\u00f6nau", pisteKm: 109, lifts: 45, dayPass: "\u20ac68.50",
        skiNotes: "Family-friendly, free ski bus, kids free with parent 3-day pass",
        price: "On request", priceModel: "On request",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: true, wifi: true, parking: true, gameRoom: true,
        strengths: "Closest drive (1h20), 44 beds, all ensuite, pets welcome, free ski bus, 2 group rooms",
        warnings: "Prices on request",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/gruppen-selbstversorgerhaus-klammrast-wildschoenau-oberau-hs11216.html",
        image: "https://www.gruppenhaus.de/mx_11216_a_6311_Wildsch%C3%B6nau+-+Oberau_Gruppen-Selbstversorgerhaus+KLAMMRAST_Klammstrasse+167.webp?q=20250712215132",
        tier: "top"
    },
    {
        name: "N15 Selbstversorgerh\u00fctte",
        location: "Hirschegg, Kleinwalsertal",
        country: "Austria",
        lat: 47.337596, lng: 10.173724,
        rank: 6, score: 34, beds: 48, rooms: 8,
        elevation: "1124m",
        drive: "2h", driveKm: 180, trainTime: "~2h40", trainChanges: "1",
        trainNotes: "Train to Oberstdorf, bus into Kleinwalsertal. Valley only accessible from Germany",
        skiArea: "Oberstdorf-Kleinwalsertal", pisteKm: 130, lifts: 48, dayPass: "\u20ac68.70",
        skiNotes: "Fellhorn, Kanzelwand, Nebelhorn, Ifen. Excellent variety",
        price: "~\u20ac2,960/night flat", priceModel: "Flat rate",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "Biggest capacity (48), 130km skiing, excellent winter hiking, easy train, panoramic terrace",
        warnings: "Expensive: ~\u20ac2,960/night, possible \u20ac2k weekend surcharge",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/n15-selbstversorgerhuette-im-kleinwalsertal-bis-zu-48-personen-hirschegg%2C-kleinwalsertal%2C-v-hs12873.html",
        image: "https://www.gruppenhaus.de/mx_12873_a_87561_Oberstdorf_N15+-+Selbstversorgerh%C3%BCtte+im+Kleinwalsertal_Nebenwasser+15.webp",
        tier: "solid"
    },
    {
        name: "Haus Canisius",
        location: "Matrei am Brenner, Tirol",
        country: "Austria",
        lat: 47.13363, lng: 11.45975,
        rank: 9, score: 31, beds: 31, rooms: 11,
        elevation: "990m",
        drive: "1h 30min", driveKm: 155, trainTime: "~2h", trainChanges: "1",
        trainNotes: "Brenner mainline \u2014 best train link of all options",
        skiArea: "Bergeralm Steinach", pisteKm: 29, lifts: 7, dayPass: "\u20ac57.30",
        skiNotes: "Night skiing. Stubaier Gletscher 30min drive",
        price: "\u20ac850\u20131,250/night", priceModel: "Flat rate",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "Best train link (Brenner, 2h), catering options (B&B/half/full board), 2 seminar rooms",
        warnings: "Small local ski area (29km)",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/haus-canisius-im-st.-michael-alpin-retreat-matrei-am-brenner-hs12729.html",
        image: "https://stm.tirol/images/startseite/st-michael-aussen-ansicht-sommer.jpg",
        tier: "solid"
    },
    {
        name: "Johannishof im Allg\u00e4u",
        location: "Nesselwang, Bavaria",
        country: "Germany",
        lat: 47.635292, lng: 10.632148,
        rank: 10, score: 30, beds: 33, rooms: 7,
        elevation: "867m",
        drive: "1h 25min", driveKm: 125, trainTime: "~2h30", trainChanges: "1",
        trainNotes: "Train via Kempten to Nesselwang, good rail link",
        skiArea: "Alpspitze Nesselwang", pisteKm: 8, lifts: 5, dayPass: "\u20ac44",
        skiNotes: "Small, good for beginners. K\u00f6nigscard includes many free activities",
        price: "\u20ac18\u201346/pp/night", priceModel: "Per person",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: true,
        strengths: "Working farm, 1h25 drive, good train, K\u00f6nigscard, own sledding hill, historic tiled stove room",
        warnings: "Small ski area (8km only)",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/johannishof-im-allgaeu-herzlich-willkommen-nesselwang-hs10449.html",
        image: "https://www.gruppenhaus.de/mx_10449_a_87484_Nesselwang_Johannishof+im+Allg%C3%A4u_Schneidbach+16.webp?q=20250918133217",
        tier: "solid"
    },
    {
        name: "Franzls H\u00fctte",
        location: "Nauders, Tirol",
        country: "Austria",
        lat: 46.887753, lng: 10.501707,
        rank: 12, score: 29, beds: 28, rooms: 10,
        elevation: "1394m",
        drive: "2h 30min", driveKm: 210, trainTime: "~4h15", trainChanges: "2-3",
        trainNotes: "Train to Landeck-Zams, then bus to Nauders. Remote by PT",
        skiArea: "Nauders Bergkastel", pisteKm: 75, lifts: 11, dayPass: "\u20ac67",
        skiNotes: "Snow-sure at altitude, 3-country pass (AT/CH/IT), uncrowded",
        price: "\u20ac18\u201325/pp/night", priceModel: "Per person",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "Budget winner (\u20ac18-25/pp), 75km skiing, 3-country pass, high altitude, terrace + grill",
        warnings: "B180 Reschenpass under construction until end 2026. Only 28 beds. Poor train link",
        dealbreaker: "Only 28 beds",
        link: "https://www.gruppenhaus.de/franzls-huette-tiroler-oberland-nauders-hs11235.html",
        image: "https://www.gruppenhaus.de/mx_11235_a_6543_Nauders++%C3%96sterreich_Franzls+H%C3%BCtte_Nauders+5.webp?q=20260102113500",
        tier: "solid"
    },
    {
        name: "H\u00f6llwart Selbstversorgerhaus",
        location: "Goldeggweng, Salzburg",
        country: "Austria",
        lat: 47.316177, lng: 13.034937,
        rank: 15, score: 24, beds: 33, rooms: 7,
        elevation: "854m",
        drive: "2h", driveKm: 170, trainTime: "~3h45", trainChanges: "2",
        trainNotes: "Train to Schwarzach-St.Veit, bus to Goldegg",
        skiArea: "Local lifts CLOSED", pisteKm: 0, lifts: 0, dayPass: "N/A",
        skiNotes: "Main lifts permanently closed 2024/25. Nearest: St. Johann/Ski Amad\u00e9 12km",
        price: "\u20ac410\u2013500/night flat", priceModel: "Flat rate (up to 20 ppl)",
        sauna: true, saunaDetails: "Outdoor sauna",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: true,
        strengths: "Outdoor sauna, games room, cheap flat rate, football pitch, fire pit",
        warnings: "SKI LIFTS PERMANENTLY CLOSED. NO PARTY GROUPS rule",
        dealbreaker: "Ski lifts closed + no parties",
        link: "https://www.gruppenhaus.de/hoellwart-selbstversorgerhaus-50410-000024-2020-goldeggweng-hs10689.html",
        image: "https://www.gruppenhaus.de/mx_10689_a_5622_Goldegg_Hoellwart+_Boden+10.webp?q=00000000000000",
        tier: "issue"
    },
    {
        name: "KSJ-Freizeithaus Pfelders",
        location: "Pfelders, Moos in Passeier",
        country: "Italy",
        lat: 46.7956, lng: 11.0898,
        rank: 16, score: 21, beds: 38, rooms: 8,
        elevation: "1632m",
        drive: "3h", driveKm: 245, trainTime: "6h+", trainChanges: "3+",
        trainNotes: "Train to Meran via Brenner+Bozen, bus to Pfelders. Only 2 buses/day",
        skiArea: "Pfelders", pisteKm: 18, lifts: 4, dayPass: "~\u20ac55",
        skiNotes: "Tiny but charming. Very snow-sure at altitude. Car-free village",
        price: "\u20ac13\u201325/pp/night", priceModel: "Mixed",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "Highest village (1632m), cheapest, stunning Texelgruppe nature, car-free tranquility",
        warnings: "Very remote, 18km piste, supermarket 20-45min, only 2 buses/day",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/ksj-freizeithaus-widum-pfelders-moos-in-passeier-hs6096.html",
        image: "https://www.gruppenhaus.de/mx_6096_a_92224_Amberg_KSJ-Freizeithaus+_Pfelders+Kirchplatz+1.webp?q=20230323094504",
        tier: "issue"
    },
    {
        name: "Bergheim Maria Trost",
        location: "Nesselwang, Bavaria",
        country: "Germany",
        lat: 47.60813, lng: 10.51114,
        rank: 17, score: 18, beds: 24, rooms: 6,
        elevation: "1123m",
        drive: "1h 25min", driveKm: 125, trainTime: "~2h30", trainChanges: "1",
        trainNotes: "Good rail link, but winter road access to house is impossible",
        skiArea: "Alpspitze Nesselwang", pisteKm: 8, lifts: 5, dayPass: "\u20ac44",
        skiNotes: "Same small area as Johannishof",
        price: "\u20ac125\u2013264/night flat", priceModel: "Flat rate",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "Cheapest flat rate, chapel on-site",
        warnings: "NO CAR ACCESS Nov\u2013May. 45min uphill walk only in winter",
        dealbreaker: "No vehicle access in winter",
        link: "https://www.gruppenhaus.de/bergheim-maria-trost-nesselwang-hs3754.html",
        image: "https://www.gruppenhaus.de/mx_3754_a_86150_Augsburg_Bergheim_Maria+Trost+Allee+100.webp?q=20240328084626",
        tier: "issue"
    },
    // === NEW HOUSES (6) ===
    {
        name: "Gruppenhaus Brixen",
        location: "Brixen im Thale, Tirol",
        country: "Austria",
        lat: 47.45, lng: 12.25,
        rank: 3, score: 36, beds: 34, rooms: 16,
        elevation: "~794m",
        drive: "1h 25min", driveKm: 121, trainTime: "~1h40", trainChanges: "1",
        trainNotes: "Train via W\u00f6rgl, very fast connection",
        skiArea: "SkiWelt Wilder Kaiser-Brixental", pisteKm: 275, lifts: 81, dayPass: "\u20ac68.50\u201376",
        skiNotes: "Austria's largest connected ski area! Ski bus 230m from door. 620-1869m",
        price: "\u20ac1,100\u20133,250/night flat", priceModel: "Flat rate",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: true, wifi: false, parking: false, gameRoom: true,
        strengths: "275km SkiWelt (largest connected!), all 16 rooms ensuite + TV, 1h25 drive, fastest train (1h40), NYE village party",
        warnings: "Sun-to-Sun full week booking only in winter. Ski pass \u20ac438/6-day",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/gruppenhaus-brixen-brixen-im-thale-hs12080.html",
        image: "https://www.gruppenhaus.de/mx_12080_a_1617+KE_Westwoud_Gruppenhaus+Brixen_Brixenbach+24.webp?q=20240118114639",
        tier: "top"
    },
    {
        name: "Homebase Zillertal",
        location: "Zillertal (nr Mayrhofen), Tirol",
        country: "Austria",
        lat: 47.16, lng: 11.86,
        rank: 6, score: 34, beds: 30, rooms: 11,
        elevation: "~630m",
        drive: "2h", driveKm: 160, trainTime: "~2h40", trainChanges: "1",
        trainNotes: "Train to Jenbach, Zillertalbahn to Mayrhofen",
        skiArea: "Mountopolis Mayrhofen", pisteKm: 142, lifts: 61, dayPass: "\u20ac52\u201376",
        skiNotes: "142km piste, 630-2500m. Part of larger Zillertal region",
        price: "On request", priceModel: "On request",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "142km Mayrhofen skiing, historic 200yr farmhouse, fireplace room, 5min to ski bus, lively NYE area",
        warnings: "NYE week 2025/26 already SOLD OUT \u2014 book very early! Ski pass \u20ac384/6-day",
        dealbreaker: null,
        link: "https://simsalabim-reisen.de/unterkunft/selbstversorger-unterkunft-zillertal/",
        image: "https://simsalabim-reisen.de/wp-content/uploads/2021/02/Simsalabim_Reisen-Unterkuft-Zillertal.jpg",
        tier: "solid"
    },
    {
        name: "Gruppenhaus Tuxertal",
        location: "Vorderlanersbach, Zillertal",
        country: "Austria",
        lat: 47.13, lng: 11.78,
        rank: 12, score: 29, beds: 30, rooms: 13,
        elevation: "~1250m",
        drive: "2h 10min", driveKm: 148, trainTime: "~3h45", trainChanges: "2",
        trainNotes: "Train to Jenbach, Zillertalbahn to Mayrhofen, bus to Vorderlanersbach",
        skiArea: "Hintertux Glacier + Mayrhofen", pisteKm: 204, lifts: 82, dayPass: "\u20ac49\u201358 (glacier)",
        skiNotes: "Austria's only year-round glacier skiing! Up to 3250m",
        price: "On request", priceModel: "On request",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: true, parking: false, gameRoom: true,
        strengths: "Heated ski storage + boot warmers, farm animals, 7 mountain huts on foot, wood-fired oven, glacier skiing",
        warnings: "Listing page DOWN (404). Must bring own bedding/towels. Contact via huettenland.com. Ski pass \u20ac384/6-day",
        dealbreaker: null,
        link: "https://www.huettenland.com/huette.php?objektID=7",
        image: "https://www.huettenland.com/fotos/huetten_klein/7/202303100856470.Gruppenhaus-Tuxertal.jpg",
        tier: "solid"
    },
    {
        name: "Gruppenhaus Krimml",
        location: "Krimml, Salzburg",
        country: "Austria",
        lat: 47.22, lng: 12.17,
        rank: 12, score: 29, beds: 31, rooms: 12,
        elevation: "~1076m",
        drive: "2h 10min", driveKm: 186, trainTime: "~3h45", trainChanges: "2",
        trainNotes: "Via Zell am See + Pinzgauer Lokalbahn (only 4 connections/day)",
        skiArea: "Zillertal Arena + Wildkogel-Arena", pisteKm: 225, lifts: 72, dayPass: "\u20ac54\u201364",
        skiNotes: "Two ski areas nearby. Ski bus 100m. Near Krimml Waterfalls",
        price: "\u20ac594\u20131,070/night (12 ppl) + \u20ac32\u201342/extra pp", priceModel: "Mixed",
        sauna: true, saunaDetails: "Finnish sauna",
        kitchen: true, ensuite: true, wifi: true, parking: false, gameRoom: true,
        strengths: "Finnish sauna, games room (billiards, darts, foosball), cellar bar, balcony rooms, Krimml Waterfalls, ski pass \u20ac384/6-day",
        warnings: "Only 4 train connections/day (Pinzgauer Lokalbahn). Gerlos Pass tricky in heavy snow. Quietest NYE of all options",
        dealbreaker: null,
        link: "https://buchen.gruppenchalets.com/Oesterreich/Salzburg/Hohe.Tauern/Gruppenhaus.Krimml.Kitzbueheler.Alpen",
        image: "https://www.gruppenchalets.com/wp-content/uploads/classified-listing/2024/07/gruppenhaus-krimml-aussen-01.jpg",
        tier: "solid"
    },
    {
        name: "Schrempfhof",
        location: "Flachau, Salzburg",
        country: "Austria",
        lat: 47.35, lng: 13.39,
        rank: 8, score: 33, beds: 32, rooms: 16,
        elevation: "~920m",
        drive: "1h 50min", driveKm: 200, trainTime: "~3h05", trainChanges: "1-2",
        trainNotes: "Train via Radstadt, then bus to Flachau",
        skiArea: "Snow Space Salzburg / Ski Amad\u00e9", pisteKm: 210, lifts: 69, dayPass: "\u20ac52\u201362",
        skiNotes: "210km local (Snow Space), 760km Ski Amad\u00e9 network. 10-15min walk to Space Jet lift",
        price: "\u20ac47/pp/night (\u20ac1,504/day)", priceModel: "Per person / flat",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: true, wifi: true, parking: true, gameRoom: true,
        strengths: "210km local + 760km Ski Amad\u00e9 network, all 16 rooms ensuite, gastro kitchen + bar, boot dryer, linens included, best ski pass value (\u20ac352/6-day)",
        warnings: "Min 6 nights in winter. NYE surcharge \u20ac70/room (\u20ac1,120 extra for 16 rooms). \u20ac47/pp. Tourist tax \u20ac1.50/pp/night. No pets",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/schrempfhof-flachau-hs12085.html",
        image: "https://www.gruppenhaus.de/mx_12085_a_5542_Flachau_Schrempfhof_Schrempf-Rosnergasse+175.webp?q=20231225190323",
        tier: "solid"
    },
    {
        name: "Gruppenhaus Alpengl\u00fcck",
        location: "Kirchdorf in Tirol",
        country: "Austria",
        lat: 47.55, lng: 12.44,
        rank: 4, score: 35, beds: 35, rooms: null,
        elevation: "~640m",
        drive: "1h 20min", driveKm: 114, trainTime: "~2h50", trainChanges: "1-2",
        trainNotes: "Train via W\u00f6rgl or Kitzb\u00fchel line",
        skiArea: "SkiStar St. Johann / KitzSki", pisteKm: 40, lifts: 10, dayPass: "~\u20ac52",
        skiNotes: "40km local (St. Johann), 233km KitzSki network available. Supermarket 500m",
        price: "\u20ac26\u201355/pp or \u20ac1,100\u20131,900/night flat", priceModel: "Per person / flat",
        sauna: true, saunaDetails: "New sauna area",
        kitchen: true, ensuite: false, wifi: false, parking: false, gameRoom: false,
        strengths: "New sauna, KitzSki network, shortest drive (1h20), supermarket 500m, cheapest ski pass (\u20ac308/6-day), NYE fireworks in 4 villages",
        warnings: "Local area only 40km. Limited online info",
        dealbreaker: null,
        link: "https://www.gruppenhaus-tirol.at/",
        image: "https://www.gruppenhaus-tirol.at/userdata/7503/pid/80446/pageElem/23649/29943/20231125_122354_Kopie.jpg",
        tier: "top"
    },
    // === LAST YEAR'S HOUSE (reference) ===
    {
        name: "Marienhof auf der H\u00f6he",
        location: "Niederthai, \u00d6tztal, Tirol",
        country: "Austria",
        lat: 47.1259442, lng: 10.9697943,
        rank: 10, score: 30, beds: 58, rooms: 13,
        elevation: "1633m",
        drive: "2h 05min", driveKm: 170, trainTime: "~3h10", trainChanges: "1",
        trainNotes: "Train to \u00d6tztal Bahnhof (2h25, from \u20ac13), bus 4194 (44min) to Niederthai",
        skiArea: "Niederthai (local) / S\u00f6lden", pisteKm: 144, lifts: 31, dayPass: "\u20ac36 local / \u20ac65 S\u00f6lden",
        skiNotes: "4km beginner area at doorstep. Free ski bus to S\u00f6lden (144km, 25km) and Hochoetz (41km, 20km)",
        price: "\u20ac6\u201312/pp + \u20ac5 tax", priceModel: "Per person",
        sauna: false, saunaDetails: "",
        kitchen: true, ensuite: false, wifi: true, parking: true, gameRoom: true,
        strengths: "LAST YEAR'S HOUSE. Huge capacity (58-64), cheapest (\u20ac6-12/pp), 1633m altitude, pro gastro kitchen, billiards/darts/foosball, ski slope at door, free ski bus to S\u00f6lden",
        warnings: "Shared bathrooms only. Utilities extra. Min 27-30 ppl. Local skiing tiny (4km). Supermarket 7km away",
        dealbreaker: null,
        link: "https://www.gruppenhaus.de/marienhof-auf-der-hoehe-umhausen-hs9218.html",
        image: "https://www.gruppenhaus.de/mx_9218_a_76297_Stutensee_Marienhof+auf+der+H%C3%B6he_Niederthai+70.webp",
        tier: "reference"
    }
];
